@startuml cd

!$targetActor = "t"
!$targetActorClass = "Teacher"
skinparam linestyle ortho
rectangle "c:Controller" as c
rectangle "$targetActor:$targetActorClass" as s
rectangle "r:Room" as r

!$targetItem = "tv"
!$targetItemClass = "TVSZ"
title  $targetActorClass Drops $targetItemClass

rectangle "$targetItem:$targetItemClass" as targetItem

c --> targetItem: 1. <<create>>

c -left-> r: 2. <<create>>
c -right-> s: 3. <<create>> 4. addItem($targetItem) \n5. dropItem($targetItem)


 

@enduml