@startuml student_room_poison_removed
title Student's room is no longer poisoned

actor Controller as c
participant "r : Room" as r
collections "r.studentList" as s

c -> r : removeEffect(POISONED)
Activate c
Activate r
loop every s:Student in studentList
r -> s : roomCleanFromPoison()
end

@enduml