@startuml student_enter_teacher
title Student enters room with teacher(s)

actor Controller as c
participant "s : Student" as s
participant "r : Room" as r


c -> s : move(r)
Activate c
Activate s
s -> r : addStudent(s)


Activate r
r --> s : true
Deactivate s
Deactivate c
r -> s : teacherAttacked()
Deactivate r
Activate s
Deactivate s


@enduml