@startuml teacher_enter_poison
title Teacher enters poisoned room

actor Controller as c
participant "t : Teacher" as s
participant "r : Room" as r


c -> s : move(r)
Activate c
Activate s
s -> r : addTeacher(s)


Activate r
r --> s : true
Deactivate s
Deactivate c
r -> s : roomPoisoned()
Activate s
Deactivate s
Deactivate r


@enduml