@startuml teacher_enter_empty
title Teacher enters empty room

actor Controller as c
participant "t : Teacher" as s
participant "r : Room" as r


c -> s : move(r)
Activate c
Activate s
s -> r : addTeacher(t)


Activate r
r --> s : true
Deactivate r
Deactivate s
Deactivate c

@enduml