@startuml
title Pair Transistor

actor Controller as c order 10
participant "t1 : Transistor" as Transistor order 30
participant "s : Student" as Student order 20
participant "t2 : Transistor" as Transistor2 order 40
participant "r : Room" as Room order 50

c -> Transistor : pairTransistor(t2)
activate Transistor



                Transistor -> Transistor2: setPair(t1)

                    activate Transistor2


                    |||
                    Transistor <-- Transistor2
                    deactivate Transistor2


    c <-- Transistor 
deactivate Transistor




@enduml