@startuml
title Transistor States

    [*] --> Active

    state Active {
        [*] -> UNCOUPLED
        UNCOUPLED --> COUPLED : couple(t1) / setCouple(t1)
        UNCOUPLED <-- COUPLED : uncouple(t1) / unsetCouple(t1)
        UNCOUPLED <-- COUPLED : pickUpTransistor(p)
        --
        [*] -> UNACTIVE
        UNACTIVE --> ACTIVE : activateTransistor(c)[COUPLED]
        UNACTIVE --> UNACTIVE : activateTransistor(c)[UNCOUPLED]
        UNACTIVE <- ACTIVE : deactivateTransistor(c)
        UNACTIVE <- ACTIVE : placeTransistor(p)[pair PLACED] / teleport(c)
        UNACTIVE <- ACTIVE : uncouple(t1)
        --
        [*] -> UNPLACED
        UNPLACED -> PLACED : placeTransistor(t1)
        UNPLACED <-- PLACED : pickUpTransistor(t1)
    }


@enduml