@startuml
title Student uses Transistor

actor Controller as c order 10
participant "t1 : Transistor" as Transistor order 30
participant "s : Student" as Student order 20
participant "t2 : Transistor" as Transistor2 order 40
participant "r : Room" as Room order 50

c -> Student : useTransistor(t1)
activate Student

    group assert
        Student -> Student : {t1 in itemList}
    end

    Student -> Transistor : activateTransistor(s)
    activate Transistor
        alt pair is set and placed

            Transistor -> Transistor2: teleportToTransistor(s)
            activate Transistor2

                Transistor2 -> Room: teleportToRoom(s)
                activate Room
                    Room -> Room: Move(s)
                    Transistor2 <-- Room
                deactivate Room
                
                Transistor <-- Transistor2
            deactivate Transistor2

        end

        Student <-- Transistor
    deactivate Transistor


    c <-- Student 
deactivate Student




@enduml