@startuml character_states

[*] --> Character
state Character {
    [*] --> ALIVE
    ALIVE -> UNCONSCIOUS : setState(UNCONSCIOUS)
    ALIVE -> DEAD : setState(DEAD)
    state UNCONSCIOUS {
        [*] -> RUNNING : startTimer()
    }
    RUNNING --> ALIVE: setState(ALIVE) [timer finished]
    UNCONSCIOUS --> DEAD : setState(DEAD)
}