@startuml
title Student uses Cheese

actor Controller as c order 1
collections Item as Item order 30
participant Student order 20
participant Room Order 60
participant Cheese order 40

c -> Student : listItems()
Student --> c : items
c -> Student : useItem(idx)
Student -> Item : useItem(Student)
Item -> Cheese : Student.accept(Cheese)
Cheese -> Room : setState(POISONED)


@enduml