@startuml
title Student uses Sponge

actor Controller as c order 1
collections Item as Item order 30
participant Student order 20
participant Sponge order 40
participant Room order 50
collections Teacher as t order 60

c -> Student : listItems()
Student --> c : items
c -> Student : useItem(idx)
Student -> Item : useItem(Student)

Item -> Sponge : Student.accept(Sponge)
Sponge -> Room : listTeacher()
Activate Sponge
Room --> Sponge : teachers
Sponge -> t : setState(unconscious) 
Deactivate Sponge

@enduml