@startuml
title Player picks up item

actor Controller as c
collections Item

c -> Room : listItems()
Room --> c : items

Activate Player
c -> Player : addItem(Item)
Alt If Inventory not Full
Player -> Item : AddItem(Item)
Player -> Room : removeItem()
end
Deactivate Player
    
@enduml