@startuml teacher_attacks

title Teacher Attacks: Item interaction
participant "s:Student" as s
participant "i:Item" as i
participant "b:isSaved" as b

s -> i : TeacherAttacked(this)
activate i
activate s
s -> b : <<create>>
activate b
s --> b : false

alt i:Item is TVSZ 
    alt hitpoints > 0
        i --> s : true
        s --> b : true
    else
        i --> s : false
    end
else i:Item is Beer 
    alt inactive
        i -> Controller : setTimer()
        activate Controller
            Controller -> i : setState(running)
        deactivate Controller
        i --> s : true
        s --> b : true
    else running
        i --> s : true
        s --> b : true
    else disabled
        i --> s : false
    end
else 
    i --> s : false
end

alt b == true
    s -> s : setState(DEAD)
end
    
@enduml