@startuml player_poisoned_item_interaction

title Player Poisoned: Item interaction
participant "s:Student" as s
participant "i:Item" as i
participant "b:isSaved" as b

s -> i : RoomPoisoned(this)
activate i
activate s
i -> i : setPlayer(s)
s -> b : <<create>>
activate b
s --> b : false

alt i:Item is Mask
    alt functional == true
        i -> Timer : startTimer(time)
        i --> s : true
        s --> b : true
    opt timer runs out
        Timer -> i : timerEnd()
        activate i
        i -> i : setFunctional(false)
        i -> s : roomPoisoned(this)
        deactivate i
    end

    else
        i --> s : false
    end
else
    i --> s : false
    deactivate i
end

s -> b : get()
b --> s : b
deactivate b

alt b == true
    s -> s : setState(UNCONSCIOUS)
    activate s
    loop every i item in itemList
        s -> s : removeItem(i)
        s -> "r:Room" : addItem(i)
        deactivate s
    end
    s -> Timer : startTimer(time)
    activate Timer
    Timer -> s : timerEnd()
    deactivate Timer
    s -> s : setState(ALIVE)
end

@enduml
