@startuml hms

title Cheese timer
participant "Controller" as c
participant "r:Room" as r
participant "s:Student" as s
participant "ch:Cheese" as ch
participant "Timer"


c -> s : useItem(ch)
activate s
s -> ch : useItem(s)
activate ch
ch -> s : getRoom()
s --> ch : r
ch -> Timer : startTimer()
activate Timer
ch -> r : addEffect(POISONOUS)
activate r
r -> s : RoomPoisoned()
Timer -> ch : timerEnd()
deactivate Timer
ch -> r : removeEffect(POISONOUS)
r -> s : RoomCleanFromPoison()
deactivate r
deactivate s

@enduml