@startuml pi
title "Student picks paired Transistor"

participant "c:Controller" as c
participant "s:Student" as s
participant "t:Transistor" as i
participant "r:Room" as r

c -> s : pickUp(i)
activate s
s -> i : pickUp(s)
activate s
activate i
i -> i : room == null
i -> r : removeEffect(TRANSISTOR_INSIDE)
activate r
r --> i
deactivate r
i -> s : addItem(t)
deactivate s
deactivate i
s -> r : removeItem(i)
activate r
r --> s 
deactivate r
s --> c
deactivate s

@enduml