@startuml student_leave_poison
title Student leaves poisoned room

actor Controller as c
participant "s : Student" as s
participant "r : Room" as r1
participant "emptyRoom : Room" as r2

c -> s : move(r2)
Activate c
Activate s
s -> r2 : addStudent(s)


Activate r2
r2 --> s : true
Deactivate s
Deactivate c
r2 -> s : roomCleanFromPoison()
Deactivate r2
Activate s
Deactivate s


@enduml