@startuml room_cannot_merge_student
title Room cannot merge student

actor Controller
participant "r1: Room" as r1
participant "r2: Room" as r2
participant "s: Student" as s

Controller -> r1 : Merge(r2)
r1 --> Controller : false
@enduml
