@startuml TeacherAttacks
title Teacher Enters Room
collections teacherList as tl
collections studentList as sl

Teacher -> Szoba : enter
Szoba -> tl : addTeacher()
Szoba -> sl : getSize()
sl -> Szoba : size

alt size > 0

    loop every student in studentList
        Szoba -> sl : students.update(TEACHER_ENTERS)

    end
end
@enduml