@startuml Student uses Beer
title Student uses Beer

actor Controller as C
participant "s : Student" as s
participant "b : Beer" as b
actor Timer as t

C -> s : useItem(b)
Activate C
Activate s
s -> b : usedByStudent(s)
Activate b
alt state == INACTIVE
b -> t : startTimer(time)
b -> b : setState(RUNNING)


end
Deactivate b
Deactivate s
Deactivate C

@enduml