@startuml Student uses Beer
title Student uses Beer

actor Controller as C
participant "s : Student" as s
participant "b : Beer" as b
actor Timer as t

C -> s : useItem(b)
Activate C
Activate s
s -> b : usedByStudent(s)
Activate b
alt isUsed == false
b -> t : startTimer(time)
Activate b
Activate t
t --> b : timeUp()
Deactivate b
Deactivate t
end
Deactivate b
Deactivate s
Deactivate C

@enduml