@startuml Student uses cheese
title Student uses cheese

actor Controller as C
participant "s : Student" as s
participant "c : Cheese" as c
participant "r : Room" as r
actor Timer as t

C -> s : useItem(c)
Activate C
Activate s
s -> c : usedByStudent(s)
activate c
alt isUsed == false
    c -> t : startTimer(time)
    Activate t
    c -> r : addEffect(POISONED)
    t -> c : timerEnd()
    Deactivate t
    c -> r : removeEffect(POISONED)
    Deactivate c
end
Deactivate s
Deactivate C

@enduml