@startuml Controller makes room cursed
title Controller makes room cursed

actor Controller as C
participant "r : Room" as r
participant "t : Timer" as t

Activate C
C -> r : addEffect(CURSED)
C -> t : startTimer(time)
Activate t
t -> C : endTimer()
Deactivate t
C -> r : removeEffect(CURSED)
Deactivate C

@enduml