@startuml mask_states

[*] --> Mask
state Timer

state Mask {
    state entry <<entryPoint>>
    [*] --> INACTIVE
    state INACTIVE
    state RUNNING
    state DISABLED

    entry -> DISABLED
    INACTIVE --> RUNNING : RoomPoisonous()
    RUNNING --> INACTIVE : RoomCleanFromPoison()
    RUNNING --> Timer : startTimer()
    INACTIVE -> Timer : pauseTimer()
}

Timer --> entry : timerEnd()


@enduml
