@startuml tvsz_states
title TVSZ States

        [*] -> PROTECTIVE :/ hitPoints = 3
                PROTECTIVE --> PROTECTIVE : TeacherAttacked(Teacher) / hitPoints - 1
        PROTECTIVE --> DISABLED : [hitPoints = 0]

@enduml
