
title Contorller Makes Room Cursed

actor Contorller as c
participant "r : Room" as Room
actor Timer as t

activate c
    c -> Room : addEffect(CURSED)

    activate Room
        c <-- Room
    deactivate Room

    c ->> t : startTimer(time)
deactivate c

activate t
    c <- t : timerEnd()
deactivate t
activate c
    c -> Room : removeEffect(CURSED)

activate Room
    Room --> c
deactivate Room
deactivate c
