 
@startuml
title Student survives
actor Room
 
participant Room order 10
participant Student order 20
participant Teacher order 30
/' participant Student order 40 '/
collections ItemList order 50

    Room -> Student : Update(event_type)
activate Student

        Student -> Teacher : Teacher.accept(ItemA)
        activate Teacher

            Teacher -> ItemA : visitTeacher(Teacher)
            activate ItemA
                alt no protection
                    Teacher <- ItemA : killStudent(item_owner)
                    activate Teacher
                        Teacher -> Student : Died
                    deactivate Teacher
                else  item gave protection
                    Teacher <- ItemA : failedKillStudent(item_owner)
                    activate Teacher
                        Teacher -> Student : Survived
                    deactivate Teacher
                end
            deactivate ItemA

            activate Teacher
                
                
            deactivate Teacher
        deactivate Teacher


/'         Student -> Teacher : Student.accept(ItemB)
        activate Teacher
            Teacher -> ItemB 
            activate ItemB
                Teacher <- ItemB
            deactivate ItemB

            activate Teacher
                Teacher -> Student : Died or Not
            deactivate Teacher
        deactivate Teacher '/
deactivate Student

/'     Room -> Player : PlayerEntered(Student)
    activate Player
        Player -> Student : Student.accept(ItemA)
        activate Student
        
            Student -> ItemA 
            activate ItemA
                Student <- ItemA
            deactivate ItemA

            activate Student
                Student -> Player : Died or Not
            deactivate Student

        deactivate Student '/
deactivate Player

@enduml