 
@startuml
title Step into Gassed Room
actor Controller
 

 
    Controller -> Player : Move(Target)
activate Player
    Player -> TargetRoom : AddPlayer(Player)
    activate TargetRoom
    TargetRoom -> Player : update(ROOM_POISONOUS)


@enduml