 
@startuml
title Step into Gassed Room
actor Controller
 

 
    Controller -> Student : Move(Target)
activate Student
    Student -> TargetRoom : AddPlayer(Student)
    activate TargetRoom
    TargetRoom -> Student : update(ROOM_POISONOUS)


@enduml