@startuml
title Room State



/'  OPEN : Doors Visible
    CLOSED : No doors
    POISONED : Stuns players '/

    [*] --> OPEN
    CLOSED -up-> OPEN : Curse timer is up
    OPEN -> CLOSED : Curse effect
    OPEN -> POISONED : Cheese effect
    OPEN <- POISONED : Cheese timer is up

    

@enduml