@startuml TeacherAttacks
title Student Enters Room
collections teacherList as tl
collections studentList as sl

Student -> Room : enter
activate Room
    Room -> sl : addStudent()
    activate sl
        Room -> tl : getSize()
        activate tl
            tl -> Room : size

        alt size > 0

            loop every student in studentList
                Room -> sl : students.update(TEACHER_ENTERS)

            end
        end
        deactivate sl
        deactivate tl
deactivate Room
@enduml