@startuml
title Student uses Sponge

actor Controller as c order 1
participant Student order 20
participant Sponge as i order 40
participant Room order 50
collections Teachers as t order 60

c -> Student : listItems()
activate Student
Student --> c : items
c -> Student : useItem(idx)
Student -> i : useItem(Room)
activate i
i -> Room : accept(Sponge)
activate Room
Room -> i : visitRoom(Room)
i -> Room : listTeachers()
Room --> i : teachers
i -> t : setState(unconscious) 

@enduml