@startuml pickupItem
title Player picks up item

actor Controller as c
participant "p: Player" as Player
participant "i: Item" as Item
participant "r: Room" as Room

Activate Player
c -> Player : pickUp(i)
alt p.itemList.size() < p.maxItems
  Player -> Room : removeItem(i)
  Player -> Item : pickUp(p)
  Item -> Player: addItem(i)
end

@enduml
