@startuml 
title Teacher Enters Room
collections teacherList as tl
collections studentList as sl

Teacher -> Room : enter
activate Room
    Room -> tl : addTeacher()
    activate tl
        Room -> sl : getSize()
        activate sl
            sl -> Room : size
    
        alt size > 0
            loop every student in studentList
                Room -> sl : students.update(TEACHER_ENTERS)

            end
        end
        deactivate sl
deactivate tl
deactivate Room
@enduml