@startuml ser
title Student saved by Mask
rectangle "c:Controller" as c
rectangle "m:Mask" as m
rectangle "s:Student" as s
rectangle "r:Room" as r

c --> r : 3. <<create>> \n
c --> s: 1. <<create>> \n 4. addItem(m)
c --> m : 2. <<create>> \n 5. setStudent(s) \n 6. setFunctional()


@enduml