@startuml student_enter_curse
title Student tries to enter cursed room
skinparam linestyle ortho
rectangle "c:Controller" as c
rectangle "r:Room" as r
rectangle "s:Student" as s
c --> s: 1. <<create>>\n\n3. setState(ALIVE)
c -> r: 2. <<create>>\t4. addEffect(CURSED)
@enduml