@startuml student_enter_poison
title Student enters poisoned room
skinparam linestyle ortho
rectangle "c:Controller" as c
rectangle "r:Room" as r
rectangle "s:Student" as s
c --> s: 1. <<create>>\n\n3. setState(ALIVE)
c -> r: 2. <<create>>\t4. addEffect(POISONED)
@enduml