@startuml student_enter_curse
title Teacher enters room with student(s)
skinparam linestyle ortho
rectangle "c:Controller" as c
rectangle "r:Room" as r
rectangle "s:Student" as s
rectangle "t:Teacher" as t
c --> s: 1. <<create>>\n\n2. setState(ALIVE)\n\n4. move(r)
c --> t: 6. <<create>>\n\n7. setState(ALIVE)
c -> r: 3. <<create>>\t
s->r: 5. addStudent(s)
@enduml