@startuml ser
title Sponge timer
rectangle "c:Controller" as c
rectangle "sp:Sponge" as sp
rectangle "s:Student" as s
rectangle "r:Room" as r
rectangle "t:Teacher" as t


c --> s: 1. <<create>> \n 5. addItem(sp) 
c --> sp: 2. <<create>> 
c --> r: 3. <<create>> \n 6.addStudent(s)
c --> t: 4. <<create>> \n 7. setRoom(r)

@enduml