name: Generate PlantUML Diagrams
on:
  push:
    # paths: ["**.plantuml"]
    branches: [main, pumlaction]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate PlantUML Diagrams
        uses: rotaract/plantuml-action@v1
        with:
          format: png
          pattern: 'docs/**.plantuml'

      - name: Upload Diagrams
        uses: actions/upload-artifact@v4
        with:
          name: diagrams
          path: 'docs/**/*.png'
