name: Generate PlantUML Diagrams
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate PlantUML Diagrams
        uses: rotaract/plantuml-action@v1
        with:
          format: svg
          pattern: 'docs/**.plantuml'

      - name: Generate PlantUML Diagrams
        uses: rotaract/plantuml-action@v1
        with:
          format: svg
          pattern: 'docs/**.puml'

      - name: Upload Diagrams
        uses: actions/upload-artifact@v4
        with:
          name: diagrams-${{ github.event.head_commit.message }}
          path: 'docs/**/*.svg'
