@startuml ser
title Student saved by Sponge
rectangle "c:Controller" as c
rectangle "sp:Sponge" as sp
rectangle "s:Student" as s
rectangle "r:Room" as r
rectangle "t:Teacher" as t

c --> s: 1. <<create>> \n 5. pickUp(sp) \n 9. setRoom(r)
s -> sp : 6. pickUp(s)
sp -> s : 8. addItem(sp)
sp -> sp : 7. startTimer()
c --> t: 2. <<create>> \n 10. setRoom(r)
c --> r: 3. <<create>> \n 
c --> sp : 4. <<create>>

@enduml